spring:
  application:
    name: todo
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  #MySql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/clush?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      url: jdbc:mysql://localhost:3306/clush?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      username: jung # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      password: jung # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#swagger
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0 #사용하는 버전을 명시
    packagesToScan: mokindang.jubging #api-docs 의 스캔 범위를 지정
    path: /v3/api-docs #api 문서 확인 경로, localhost:8080/v3/api-docs 로 접속

  swagger-ui:
    operationsSorter: method #method 기준으로 정렬, 그외 alpha 로 정렬 가능
    path: /todo #swagger ui 의 api 문서 확인 경로 defalut 는 /swagger-ui.html 이다.

  default-consumes-media-type: application/json #기본으로 설정되는 미디어타입 지정
  auto-tag-classes: true #오토 태그 기능 활성화
  groups:
    enabled: false #api 그룹 기능, default는 true 이나 당장 사용하지 않기에 false 로 지정

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#서버포트
server:
  port: 8080